package com.ebingo.backend.common;

import java.util.List;

public final class Constants {
    public static final List<String> PUBLIC_API_PATHS_FOR_FILTER = List.of(
            "/api/auth",
            "/swagger-ui",
            "/v3/api-docs",
            "/swagger-resource",
            "/webjars",
            "/docs",
            "/api/v1/secured/billing/payment/chapa/webhook",
            "/api/v1/secured/billing/payment/pesapal/IPN"
    );

    public static final List<String> PUBLIC_API_ENDPOINTS_FOR_ACCESS = List.of(
            "/",
            "/api/v1/users",
            "/api/v1/users/**",
            "/api/v1/public/common/languages/**",
            "/api/auth/**",
            "/swagger-ui/**",
            "/v3/api-docs/**",
            "/swagger-resource/**",
            "/webjars/**",
            "/docs",
            "/api/v1/secured/billing/payment/chapa/webhook",
            "/api/v1/secured/billing/payment/pesapal/IPN",
            "ws://localhost:8080/ws/game",
            "/actuator/**"
    );


    public static String getRandomName() {
        List<String> randomNames800 = List.of("Hermela", "Bontuu", "Gammachuu", "Mulumebrat", "Segen", "Hiyob", "Birruu", "Eyerus",
                "Betty", "Neyat", "Amanuel", "Hagos", "Daganii", "Rahel", "Kidan", "Booree", "Senhab",
                "Haile", "Ayantu", "Abdulrahman", "Ayichaa", "Kidane", "Roke", "Jatani", "Mahider",
                "Genetawit", "Lensa", "Kalai", "Teklit", "Saron", "Badhane", "Firaol", "Nardos",
                "Mussie", "Girmay", "Yordanos", "Aster", "Xayibaa", "Natan", "Kidisti", "Asefa",
                "Falmata", "Birhanu", "Amanuel", "Arsema", "Halaaf", "Zewdu", "Hagos", "Abduselam",
                "Hirut", "Hagos", "Xraxaa", "Lidiya", "Feven", "Hagos", "Muhanit", "Gutaamaa", "Ruqiya",
                "Dhibbaa", "Hagos", "Selamawit", "Dogoggoraa", "Jatani", "Sanbatuu", "Kalai", "Desta",
                "Ragaa", "Eleni", "Tsige", "Salina", "Zemenay", "Boonaa", "Guta", "Aman", "Nati",
                "Hermela", "Hagos", "Ruqiya", "Samrawit", "Fitsum", "Eyerus", "Hagos", "Turaabaa",
                "Ayub", "Muna", "Hawani", "Gutaamaa", "Biruk", "Najat", "Bariisaa", "Kidisti",
                "Kibrom", "Amina", "Samira", "Helina", "Guta", "Tadelech", "Duresa", "Berhanu", "Lilay",
                "Feno", "Ayyaantuu", "Melisa", "Raggat", "Biruktawit", "Hedun", "Saron", "Adoolessa",
                "Meklit", "Ruke", "Idris", "Lensa", "Xilillii", "Weyni", "Samia", "Welde", "Meles",
                "Dagmawi", "Semhar", "Liiban", "Miki", "Senait", "Mahider", "Hagos", "Fitsum", "Debebe",
                "Xurraayaa", "Melat", "Hedun", "Ezra", "Xayibaa", "Sali", "Gaaromsaa", "Konjit",
                "Gammachis", "Dhibbaa", "Kalkidan", "Tsion", "Asefa", "Selam", "Gurmuu", "Binyam",
                "Zion", "Yonas", "Made", "Rahwa", "Birkeessaa", "Mahlet", "Sidu", "Jabrila", "Gammataa",
                "Tsion", "Rezene", "Yohanna", "Bontu", "Birhanu", "Adugna", "Guta", "Teame", "Bruktawit",
                "Gonaa", "Meti", "Kiflom", "Yonatan", "Abel", "Fayyisaa", "Kediir", "Araya", "Seenaa",
                "Weini", "Yosan", "Lemi", "Hana", "Roro", "Bontu", "Nati", "Robaa", "Jibril", "Utubaa",
                "Lami", "Jallaalaa", "Rahwa", "Dirribaa", "Biruk", "Luel", "Mulu", "Amanuel", "Jamal",
                "Mahlet", "Melka", "Xaxaa", "Sumeya", "Salim", "Girmay", "Gutuudhaa", "Xayibaa", "Senay",
                "Mulubrhan", "Rago", "Gammachuu", "Tigistuu", "Walad", "Abebe", "Bontuu", "Seid",
                "Feno", "Mebrahtu", "Abduljelil", "Amanuel", "Saron", "Kidus", "Tinsae", "Qabsituu",
                "Ayantu", "Tesfay", "Saron", "Kelile", "Henry", "Naod", "Duresa", "Ebbisaa", "Gutaamaa",
                "Tadelech", "Samiya", "Dachi", "Biruktawit", "Jatani", "Hermela", "Tesfatsion", "Hagos",
                "Dhiressaa", "Melat", "Abduseber", "Walldo", "Natan", "Tsige", "Amin", "Segen",
                "Odaa", "Abdulrahman", "Salah", "Gurmuu", "Muluwork", "Liam", "Hagos", "Senait", "Kalay",
                "Caaltuu", "Saron", "Roobsee", "Aweke", "Bethel", "Lidiya", "Eriya", "Maraki", "Freweini",
                "Xalyanii", "Biruk", "Amanuel", "Gammachuu", "Hedun", "Faye", "Xilillii", "Abebe",
                "Qajeelaa", "Gutaamaa", "Baqalaa", "Lidiya", "Hagos", "Yohannes", "Gebremedhin",
                "Melat", "Semere", "Halaaf", "Samrawit", "Amanuel", "Addisu", "Naod", "Tsion",
                "Saliha", "Ibrahim", "Senay", "Guta", "Yared", "Miki", "Dagnachew", "Ayantu", "Semhar",
                "Hana", "Irreecha", "Tadese", "Mohammed", "Aster", "Teklu", "Mahider", "Bontu", "Konjit",
                "Nani", "Yohanis", "Ruqiya", "Bruk", "Saron", "Zemen", "Hagos", "Berhane", "Gutaamaa",
                "Mahi", "Nuru", "Musa", "Amanuel", "Dachaasa", "Senait", "Liam", "Senay", "Lensa",
                "Segen", "Mulugeta", "Hawani", "Tsion", "Haftom", "Ayub", "Hagos", "Bontu", "Jamila",
                "Kidane", "Tigris", "Fikirte", "Bariisaa", "Mussie", "Teklu", "Saron", "Yonas", "Kidane",
                "Jatani", "Lidia", "Tirhas", "Roobaa", "Wubit", "Fitsum", "Tigist", "Birhanu", "Freweini",
                "Yosief", "Rahwa", "Eden", "Sami", "Nardos", "Xilillii", "Henok", "Kiros", "Gutaamaa",
                "Lior", "Dhibbaa", "Hermela", "Yohannes", "Qabsoo", "Guta", "Nati", "Bontu", "Adam",
                "Mahi", "Kibra", "Habtom", "Muna", "Helina", "Walldo", "Nebyu", "Kidane", "Biruk",
                "Hagos", "Senait", "Bariisaa", "Ayantu", "Melisa", "Duresa", "Tesfamichael", "Birhanu",
                "Ibsaa", "Saron", "Mehari", "Xurraayaa", "Fitsum", "Araya", "Aster", "Xilaahun",
                "Selam", "Kibrom", "Tadelechaa", "Kadir", "Guta", "Mulu", "Saron", "Hagos", "Hermela",
                "Dachi", "Liiban", "Muluwork", "Abdulrahman", "Qajeelaa", "Teame", "Ragaa", "Solomon",
                "Yonas", "Dhibbaa", "Segen", "Bontu", "Hagos", "Mehari", "Saron", "Fanoo", "Gutaamaa",
                "Tesfay", "Najat", "Birktawit", "Yonas", "Mahider", "Girmay", "Ayichaa", "Aster",
                "Sami", "Tsega", "Araya", "Desta", "Guta", "Lensa", "Abraha", "Daghan", "Xayibaa",
                "Mehari", "Zemenay", "Kidane", "Weyni", "Ibrahim", "Guta", "Samrawit", "Tsion", "Kidus",
                "Dachi", "Halaaf", "Xilaahun", "Saron", "Jaldesa", "Hermela", "Samia", "Hagos", "Semere",
                "Gutaamaa", "Zewdu", "Mahlet", "Xilillii", "Gammachis", "Raggat", "Natan", "Welde",
                "Hewan", "Birhanu", "Mehari", "Teklu", "Arsema", "Amina", "Samira", "Lidiya", "Amanuel",
                "Hiyob", "Bezalel", "Guta", "Amanuel", "Feven", "Jatani", "Sami", "Melisa", "Amanuel",
                "Tesfay", "Abel", "Konjit", "Rahwa", "Gurmuu", "Mahlet", "Senait", "Solomon", "Tsegay",
                "Amanuel", "Dachaasuu", "Xallyani", "Yonas", "Lense", "Niat", "Duresa", "Gutaamaa",
                "Hagos", "Xayibaa", "Biruk", "Mahi", "Senait", "Kiflom", "Senedu", "Segen", "Yohanna",
                "Nani", "Jatani", "Araya", "Kibrom", "Hagos", "Lensa", "Amanuel", "Teklit", "Mebrat",
                "Qubee", "Seenaa", "Melaku", "Gutaamaa", "Nati", "Biruk", "Senay", "Senadu", "Xayibaa",
                "Guta", "Hagos", "Gammachuu", "Ibsaa", "Tsion", "Lensa", "Aweke", "Lidiya", "Bontu",
                "Hagos", "Araya", "Semhar", "Feno", "Rahwa", "Teklu", "Selam", "Saron", "Jatani", "Hagos", "Hewan", "Lemecha", "Mekdes", "Ruth", "Ayuel", "Bersabeh", "Galana", "Hafte",
                "Sura", "Mella", "Abenezer", "Beekan", "Dirribi", "Sofanit", "Almaz", "Kadija",
                "Raya", "Dureti", "Jeylan", "Yedidia", "Ebbissa", "Amran", "Yasmin", "Mikyas",
                "Gadisa", "Azeb", "Ethio", "Saba", "Lali", "Hiywet", "Kemer", "Najib", "Aynadis",
                "Robsan", "Yetnayet", "Fatuma", "Eliasu", "Gosaye", "Beleche", "Liya", "Jallan",
                "Hanifa", "Mulualem", "Bilal", "Samina", "Asanti", "Rakeb", "Sifan", "Mikiyas",
                "Ras", "Kaleab", "Jimma", "Sofanit", "Gutu", "Rakeen", "Kaleessa", "Adey",
                "Wubit", "Raqiya", "Yodit", "Aneela", "Temam", "Meskerem", "Haadha", "Lemi",
                "Meron", "Gezahegn", "Firdows", "Abiyot", "Mebratu", "Sofa", "Nuredin", "Mahibere",
                "Tesema", "Feiza", "Dejene", "Faik", "Sofiya", "Naji", "Beshadu", "Hawi",
                "Tibarek", "Senaay", "Aadil", "Hayla", "Luul", "Addunya", "Kedir", "Werke",
                "Fiyori", "Olfaa", "Hafiza", "Raya", "Jambo", "Balina", "Abadit", "Fahim",
                "Eba", "Yohanna", "Sinda", "Dilnesaw", "Barakat", "Dursa", "Yedilfana", "Kasiim",
                "Hamda", "Nabirye", "Ashenafi", "Nuriya", "Maqala", "Rasmiya", "Sisay", "Adanech",
                "Bonaa", "Fetiya", "Wakjira", "Imam", "Kirosi", "Mintwab", "Mebrat", "Jamaludin",
                "Ashu", "Tazeb", "Duratu", "Hidat", "Xila", "Fiqadu", "Adiya", "Huriyah", "Jibriil",
                "Befkadu", "Kenas", "Sania", "Tigabu", "Hanna", "Leqa", "Xalatuu", "Aida",
                "Kaleb", "Nisir", "Ililiy", "Abugida", "Bontu", "Galgalo", "Sirak", "Hiwot",
                "Yayeh", "Afshet", "Jemal", "Falmataa", "Husna", "Amro", "Awel", "Dema",
                "Nawel", "Hagosha", "Kidanawit", "Rigbe", "Sartu", "Asab", "Nabra", "Hagosom",
                "Dalgat", "Sifoni", "Beekan", "Fikir", "Feiruz", "Xeniya", "Rakiyyu", "Lamech",
                "Jirata", "Yemisrach", "Imran", "Kubsa", "Alemseged", "Furtuna", "Walelo",
                "Harun", "Rakeel", "Alemnesh", "Aliya", "Nashon", "Kaddis", "Safia", "Tinbit",
                "Wondu", "Abigail", "Gada", "Aragaw", "Gessese", "Aqala", "Admasu", "Yesuf",
                "Sifanitu", "Tamru", "Irma", "Yaaseen", "Efrata", "Zehara", "Kalila", "Bariso",
                "Sintu", "Rahelawit", "Haileyu", "Gammachu", "Abdurazak", "Azit", "Hadaasa",
                "Temesgen", "Atem", "Nejashi", "Milkessa", "Galmee", "Abebu", "Germame",
                "Tsiyona", "Sabiina", "Bayu", "Belaynesh", "Imin", "Ayaan", "Mikiyaa",
                "Mebrek", "Sabri", "Sewit", "Girmaw", "Amna", "Kena", "Maru", "Beza",
                "Woldetensay", "Yeshi", "Maqbula", "Walid", "Qajeelchaa", "Getaneh", "Neba",
                "Kidamen", "Lamrot", "Tazkar", "Suraafaa", "Eyoel", "Malkamu", "Debritu",
                "Fiqir", "Arif", "Fida", "Titina", "Soriya", "Soliyana", "Golla", "Xumra",
                "Kelali", "Arasa", "Lila", "Yednet", "Yeman", "Junda", "Fidya", "Abbitu",
                "Gubena", "Aamer", "Sule", "Zahia", "Misgana", "Mebre", "Aadan", "Liban",
                "Misrak", "Faki", "Mekides", "Abusha", "Tameru", "Sarone", "Sora",
                "Galataa", "Abuhay", "Zahira", "Ganame", "Takale", "Serdo", "Gure",
                "Yeshiwork", "Waqgari", "Ashura", "Winta", "Fayhaa", "Luqman", "Hedase",
                "Yemsrach", "Abdi", "Amira", "Melkesha", "Gulat", "Danait", "Segni",
                "Beta", "Tena", "Wesseny", "Sheza", "Ayman", "Firomsa", "Nemera", "Ararsa",
                "Tilahuun", "Fehmiya", "Abiyotaw", "Xade", "Wirke", "Elbethel", "Dandana",
                "Kidanemariam", "Misganu", "Yoman", "Birra", "Ragad", "Naima", "Hamu",
                "Zahraw", "Yeshe", "Haylu", "Getachew", "Husniya", "Derartu", "Rifka",
                "Dawitaw", "Gaari", "Qalam", "Aday", "Miya", "Aron", "Balcha", "Abren",
                "Aidwa", "Hizbay", "Fetene", "Mika", "Rakiba", "Yaqobay", "Aifan",
                "Zekri", "Walya", "Awash", "Kelil", "Azzam", "Amine", "Talalak", "Guba",
                "Habiba", "Sebrina", "Tayib", "Ashenaf", "Bani", "Gezaw", "Helemi",
                "Biniyam", "Mekoya", "Selma", "Roba", "Lensaay", "Yasiru", "Feroz",
                "Maren", "Qosii", "Addislam", "Girmachew", "Biraanu", "Sadiya", "Bermel",
                "Taha", "Beshir", "Dura", "Jeyna", "Seina", "Fetiya", "Sultan", "Leensa",
                "Abida", "Tilahun", "Jijiga", "Jatala", "Walila", "Mekuanent", "Abdo",
                "Yusuf", "Rizq", "Xaaditu", "Fuad", "Alim", "Hanun", "Ruhama", "Selafi",
                "Abebe", "Kebede", "Tadesse", "Bekele", "Getachew", "Mulugeta", "Tesfaye", "Yared", "Solomon", "Dawit",
                "Yohannes", "Daniel", "Samuel", "Elias", "Mekonnen", "Haile", "Gebremedhin", "Gebrehiwot", "Amanuel", "Fitsum",
                "Kidane", "Berhanu", "Asfaw", "Zelalem", "Endalkachew", "Addisu", "Wondimu", "Demeke", "Biruk", "Negash",
                "Mengistu", "Tilahun", "Shiferaw", "Lemlem", "Mekdes", "Hanna", "Selam", "Saba", "Ruth", "Rahel",
                "Bethlehem", "Eden", "Feven", "Mahlet", "Meron", "Yeshi", "Tsion", "Hiwot", "Bruktawit", "Seble",
                "Almaz", "Genet", "Kalkidan", "Kidist", "Saron", "Lidya", "Nardos", "Birtukan", "Mimi", "Yordanos",
                "Fatuma", "Amina", "Khadija", "Hawa", "Halima", "Safiya", "Zainab", "Maryam", "Rahma", "Nasra",
                "Sumaya", "Nimco", "Shukri", "Ikram", "Faduma", "Layla", "Ayaan", "Amal", "Sahra", "Deqa",
                "Mohammed", "Ahmed", "Ali", "Hassan", "Hussein", "Abdulrahman", "Abdullah", "Yusuf", "Ismail", "Ibrahim",
                "Mustafa", "Mahmoud", "Khalid", "Omar", "Farah", "Nur", "Said", "Salim", "Abdirahman", "Abdullahi",
                "Jibril", "Bilal", "Harun", "Idris", "Suleiman", "Zakaria", "Anwar", "Hamza", "Yasin", "Munir",
                "Jalal", "Abdi", "Robel", "Dagmawi", "Henok", "Eyob", "Kaleb", "Natan", "Gideon", "Ephrem",
                "Petros", "Pawlos", "Markos", "Lukas", "Matheos", "Yacob", "Abraha", "Hagos", "Tesfalem", "Welde",
                "Aregawi", "Hadush", "Kiros", "Filmon", "Semere", "Meresa", "Beraki", "Fitsion", "Dawitawit", "Nahom",
                "Micael", "Samrawit", "Haben", "Senait", "Fikir", "Aster", "Mariam", "Serkalem", "Yitbarek", "Hailu",
                "Gebremariam", "Wubet", "Tigist", "Mulu", "Shewit", "Worknesh", "Frehiwot", "Yosief", "Abel", "Ezra",
                "Jemal", "Siraj", "Rashid", "Basheer", "Nabil", "Latif", "Karim", "Sharif", "Sami", "Hadi",


                "Abdinasir", "Abdimalik", "Abdifatah", "Abdikarim", "Abdirizak", "Abdishakur", "Abdulsalam", "Abdulaziz", "Abdulwahab", "Abdulqadir",
                "Abdullatif", "Abdulbasit", "Abdulrahim", "Abdulhadi", "Abduljalil", "Abdulkarim", "Abdulmannan", "Abdulnasir", "Abdulrazak", "Abdulshakur",
                "Abukar", "Aden", "Aragsan", "Asad", "Aweis", "Bashir", "Beder", "Burhan", "Daud", "Faysal",
                "Gelle", "Hersi", "Hodan", "Ilyas", "Imran", "Isse", "Jama", "Kadar", "Kassim", "Liban",
                "Mahdi", "Mukhtar", "Nuh", "Qasim", "Ridwan", "Sadiq", "Shamsudin", "Tahir", "Umar", "Wali",

                "Abiyot", "Adane", "Adisu", "Alemayehu", "Alemu", "Amare", "Aschalew", "Atsede", "Awet", "Belay",
                "Birhanu", "Chala", "Damte", "Desalegn", "Eba", "Fanta", "Fisseha", "Gashaw", "Gebreselassie", "Gebru",
                "Hadera", "Haimanot", "Hirut", "Kassahun", "Kassaye", "Kifle", "Lulseged", "Marew", "Mesay", "Misganaw",
                "Muluneh", "Nigatu", "Sahle", "Seid", "Sisay", "Teka", "Temesgen", "Tesfahun", "Tesfaldet", "Tewodros",
                "Worku", "Yalew", "Yemane", "Yeshitila", "Zerihun", "Zewde", "Zufan", "Zufanaw", "Zewditu", "Zeritu",

                "Abish", "Ader", "Adiam", "Adina", "Admas", "Alganesh", "Ameset", "Asrat", "Ataklti", "Ayana",
                "Blen", "Chernet", "Dahlak", "Efrata", "Eyayu", "Fasika", "Fenet", "Hagosay", "Hibret", "Kalki",
                "Kedus", "Lemtu", "Medhanit", "Melkam", "Muluwork", "Nigisti", "Raey", "Rediet", "Sebhat", "Senay",
                "Segen", "Sifan", "Sinet", "Tsedale", "Tsedey", "Winta", "Yabsira", "Yoftahe", "Zena", "Zufish",

                "Araya", "Berhane", "Desta", "Fikadu", "Girmay", "Habtom", "Haileselassie", "Kesete", "Kokeb", "Mehari",
                "Muluye", "Neguse", "Romel", "Sahlework", "Seare", "Teklay", "Tesfom", "Tsehaye", "Yohans", "Zemariam",
                "Abisalom", "Ananya", "Bethel", "Chaltu", "Derartu", "Dinkinesh", "Elilta", "Ferehiwot", "Gelila", "Hadas",
                "Keren", "Lensa", "Mareta", "Naol", "Qal", "Segenet", "Sifanat", "Tirunesh", "Yemisrach", "Zinash",


                "Äbëbë★", "Këbëdé☆", "Tädëssä♛", "Bëkëlë✓", "Ğëtächëw✦", "Mülügëtä♞", "Tësfäÿë⚡", "Ÿärëd☯", "Šölömøn✪", "Däwït☀",
                "Ÿöhännës✝", "Däniël♜", "Šämüël♚", "Ëliäs✧", "Mëkønnën♠", "Häïlë☘", "Ğëbrëmëdhïn⚔", "Ğëbrëhïwöt✿", "Åmänüël❖", "Fïtsüm➹",

                "Kïdänë♬", "Bërhänü☾", "Äsfäw★", "Zëlälëm✦", "Ëndälkäçhëw♛", "Äddïsü✓", "Wøndïmü⚡", "Dëmëkë✧", "Bïrük♠", "Nëgäsh☯",
                "Mëngïstü✪", "Tïläḥün♜", "Šhïfëräw♚", "Lëm·lëm✿", "Mëkdës☀", "Hännä★", "Sëläm✧", "Šäbä♠", "Rüth☯", "Rähël✪",

                "Bëth·lëhëm♛", "Ëdën✓", "Fëvën⚡", "Mählët✦", "Mërøn♚", "Ÿëšhï✿", "Tsïøn☾", "Hïwöt☀", "Brüktäwït♠", "Šëblë✧",
                "Älmåž✪", "Ğënët♛", "Kälkïdän✓", "Kïdïst⚡", "Šärøn✦", "Lïdÿä♚", "Nårdøs✿", "Bïrtükän☯", "Mïmï☀", "Ÿørdånøs♠",

                "Fätümä★", "Ämïnä✦", "Khädïjä♛", "Häwä✓", "Hälïmä⚡", "Šäfïÿä✧", "Zäïnãb♚", "Märyäm✿", "Rähmä☯", "Näšrä☀",
                "Šümäÿä♠", "Nïmcø✪", "Šhükrï♛", "Ïkräm✓", "Fädümä⚡", "Läÿlä✦", "Äÿään♚", "Ämäl✿", "Šährä☯", "Dëqä☀",

                "Møħämmëd★", "Äħmëd✦", "Älï♛", "Hässän✓", "Hüssäïn⚡", "Äbdürähmän✧", "Äbdülläh♚", "Yüsëf✿", "Ïsmäïl☯", "Ïbrähïm☀",
                "Müstëfä♠", "Mähmøüd✪", "Khälïd♛", "Ömär✓", "Färäh⚡", "Nür✧", "Šäïd♚", "Šälïm✿", "Äbdïräħmän☯", "Äbdüllähï☀",

                "Ğïbrïl★", "Bïläl✦", "Härün♛", "Ïdrïs✓", "Šülëïmän⚡", "Zäkärïyä✧", "Änwär♚", "Hämzä✿", "Yäsïn☯", "Münïr☀",

                "Røbël★", "Dägmäwï✦", "Hënøk♛", "Ëÿøb✓", "Kälëb⚡", "Nätän✧", "Ğïdëøn♚", "Ëphrëm✿", "Pëtrøs☯", "Päwløs☀",

                "Märkøs★", "Lükäs✦", "Mäthëøs♛", "Yäcøb✓", "Äbrähä⚡", "Hägøs✧", "Tësfälëm♚", "Wëldë✿", "Ärëgäwï☯", "Hädüš☀",

                "Abdinasir", "Abdinuur", "Abdirashid", "Abdisa", "Abdosh", "Abran", "Adem", "Adino", "Adola", "Adugna",
                "Ahmednur", "Ajib", "Akalu", "Alemberhan", "Alemnesh", "Alemtsahay", "Alemuay", "Alganesh", "Alula", "Amanuelit",
                "Amsalu", "Anbesaw", "Andargachew", "Andinet", "Ansha", "Arega", "Aregash", "Ariam", "Arsema", "Aschalewit",
                "Asfachew", "Asnake", "Atalay", "Awalom", "Awoke", "Ayantu", "Ayele", "Ayenew", "Aytenew", "Azeb",

                "Bahran", "Balcha", "Bamlak", "Bedilu", "Belachew", "Benti", "Berhanuay", "Beyan", "Bilisummaa", "Bishaw",
                "Blenat", "Bogale", "Bontu", "Bosena", "Buze", "Chalao", "Chanyalew", "Cherkos", "Daba", "Dagnachew",

                "Dagmawit", "Dale", "Dandena", "Debela", "Degife", "Delina", "Derese", "Destawe", "Dibaba", "Dinku",
                "Diriba", "Dula", "Eba", "Efriyem", "Eleni", "Elshaddai", "Endashaw", "Enku", "Ermias", "Esayas",

                "Fantu", "Fanos", "Fantawe", "Fekade", "Fenta", "Fetene", "Fikremariam", "Fikru", "Fissehaye", "Frezer",
                "Gadisa", "Gashaye", "Gebreab", "Gebrekidan", "Gebremeskel", "Gebresenbet", "Gebreslassie", "Gebretinsae", "Getahun", "Girmaw",

                "Habtomit", "Haderawe", "Hagosit", "Hailesilasie", "Hailush", "Haimanote", "Hanae", "Haregewoyn", "Haregot", "Hasseno",
                "Haylu", "Hiben", "Hikma", "Hilina", "Hiyaw", "Ilili", "Imanet", "Ishmael", "Itay", "Jawar",

                "Kabbo", "Kalkachew", "Kasa", "Kassahunet", "Kedir", "Kefyalew", "Kenenisa", "Ketema", "Kidus", "Kidanemariam",
                "Kirosay", "Kokebe", "Kumsa", "Lemesa", "Lensawe", "Lidet", "Likawent", "Lulit", "Mabruk", "Mahder",

                "Maleda", "Mastewal", "Meaza", "Medhanialem", "Mekuria", "Melaku", "Merhawi", "Meseret", "Mestawot", "Mihret",
                "Minale", "Mintesnot", "Moges", "Mohammednur", "Muluadam", "Mulualem", "Mulugetawe", "Muniruddin", "Naba", "Nahusenay",

                "Natnael", "Nebiyat", "Negasi", "Neima", "Nigist", "Nuhamin", "Rahelit", "Redwan", "Rehima", "Robera",
                "Sabawe", "Sabira", "Sahleworkit", "Saronit", "Seblewe", "Segenash", "Selamawit", "Semagn", "Senaitwe", "Serawit",

                "Shambel", "Shemsu", "Shibru", "Sifan", "Sileshi", "Sirak", "Sisayit", "Sofonias", "Soreti", "Subira",
                "Tahira", "Taju", "Tamirat", "Tareke", "Tegbaru", "Temam", "Tesfahunegn", "Tesfaldet", "Tewabe", "Tibebu",

                "Tigabu", "Tinsae", "Tirhas", "Tola", "Tsegaye", "Tseganesh", "Tsedalu", "Tsedeyit", "Tsige", "Wakgari",
                "Wale", "Wariyo", "Werknesh", "Wondwesen", "Wubalem", "Yabsra", "Yaredawit", "Yehualashet", "Yemiserach", "Yemata",

                "Yibeltal", "Yodit", "Yonatan", "Yoseph", "Zaid", "Zekarias", "Zelealem", "Zenabu", "Zerfe", "Zinabu");

        int randomIndex = (int) (Math.random() * randomNames800.size());
        return randomNames800.get(randomIndex);
    }
}
